help: switch from formatter module to textwrap
Issue: LINUXEXEC-16832

Since Python has deprecated the formatter module, switch to the textwrap
module instead for reflowing text.  We weren't really using any other
feature anyways.

Verified by diffing the output before & after the change and making sure
it was the same.

Then made a few tweaks to tighten up the output.

Change-Id: I0be1bc2a6661a311b1a4693c80d0f8366320ba55
Reviewed-on: https://gerrit-review.googlesource.com/c/git-repo/+/303282
Reviewed-by: Raman Tenneti <rtenneti@google.com>
Tested-by: Mike Frysinger <vapier@google.com>

python3.10 has removed the formatter module, backport this patch to fix
setup error with new buildtools.
  File "/bin/git-repo/subcmds/help.py", line 20, in <module>
    from formatter import AbstractFormatter, DumbWriter
ModuleNotFoundError: No module named 'formatter'

Backport from https://github.com/GerritCodeReview/git-repo/commit/0888a083ec6a23a75d3e681f08ef242acd862573

Signed-off-by: Changqing Li <changqing.li@windriver.com>