project.py: Adjust the retrying policy
Issue: LIN1019-6732

Before:
Max retries: 2
Sleep time: A random number between 30 and 45 seconds

Now:
Max retries: 5
Sleep time: Start from 30 seconds, increase a random number between 5 and 10
for each trying

Now it works well when:
$ repo sync -j 1000

The command was always failed before the change. There are still errors like:
fatal: read error: Connection reset by peer

But no errors like:
error: Cannot fetch <repo>

The "reset by peer" message doesn't matter since it would retry in such a case,
the real problem is the second one, and it's gone now.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Adrian Zaharia <Adrian.Zaharia@windriver.com>